### ISSUE TITLE
Supporting `*_with()` construct, similar to Rayon's `map_with()`

### ISSUE THREAD

**Issue by nyurik** [dpc/pariter#2]
Would it make sense to add `parallel_map(init, func)`?  This is similar to how Rayon allows per-thread cloning, e.g. [map_with](https://docs.rs/rayon/1.5.1/rayon/iter/trait.ParallelIterator.html#method.map_with).  Ideally cloning should only be done once per thread, not once per mapping function callback.  I could try to hack a PR if it is acceptable, but any starting pointers would be awesome.  Also, there might be too many function name combinations - as it would essentially double the number of existing functions.

**Comment by dpc** [comment]
Cloning of what exactly? :)

**Comment by dpc** [comment]
Oh dear. Of an arbitrary value? Ugh. :D

**Comment by dpc** [comment]
I guess a version with a value could be considered a generalization of the current version. The current version is kind of like  using `()` as the `T : Send + Clone`. However, I guess the lack of impl-specialization is going to get in a way.

I also can't see any way to put that `T` into `map_custom` version.

So, yeah. I guess it manipulatively explodes number of variants. Are there any other weird custom features that I'm not aware of that are going to make it even worse? :D

It seems to me that the same result can be achieved by using https://docs.rs/thread_local/latest/thread_local/#examples for those cases where someone really needs it , so I'm not sure if it's worth making maintenance more difficult. Generally `pariter` is already kind of slow in the overhead-per item, comparing to `rayon`. Sending elements items back and forth is about 200ns of overhead. I wonder how much much overhead is cloning a channel, but possibly much less than that anyway. And then `thread-local` can make it even lower, especially for values with higher cloning overhead.

So, yeah. Mixed feelings about this. It makes sense for `rayon`, because `rayon` is ultra-optimized to lower the per-item overhead, while `pariter` is not.

**Comment by dpc** [comment]
No immediate plans to do it.
